### ISSUE TITLE
Selection highlighting

### ISSUE THREAD

**Issue by eda2z** [monolifed/scite_theme#1]
I'm not sure if anyone is updating this repo but selection highlighting is broken under the latest SciTE (5.1.0). I think it actually started in 5.0.3. The selection shows white overlaying "barely visible" text. Thanks.

**Comment by monolifed** [comment]
This is definitely outdated. I will check it with scite 5.x

**Comment by monolifed** [comment]
I hope b7dd7f0 fixes the issue

**Comment by eda2z** [comment]
Thanks. That did it.
