### ISSUE TITLE
Selection highlighting during replace

### ISSUE THREAD

**Issue by eda2z** [monolifed/scite_theme#2]
I noticed that you added more changes for folding. Thanks.
You may want to add selection.inactive properties the same as selection properties. I found that without these if you are performing a Search/Replace... operation and click on the Find Next button that nothing *may* be highlighted since it reverts to the SciTE defaults.

**Comment by monolifed** [comment]
I added them. I also reduced the alpha value

**Comment by eda2z** [comment]
Thanks, I got it.
